server:
  port: 4000

spring:
  application:
    name: trace-2
  sleuth:
    sampler:
      percentage: 0.5
  zipkin:
    base-url: http://127.0.0.1:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/